name: snooper_android_example
description: Demonstrates how to use the snooper_android plugin.

publish_to: 'none'

environment:
  sdk: ">=2.17.0-27.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  snooper_android:
    path: ../

  # Dependencies for easy visualization of the retrieved data
  # not required for `snooper_android` to function
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true